name: "xUnit.net PR Build (main)"
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04, macOS-12]
    steps:
      - name: Clone source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Add MSBuild to PATH (Windows)
        uses: microsoft/setup-msbuild@v1
        if: matrix.os == 'windows-2022'

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Get .NET information
        run: dotnet --info

      - name: "Build target: BuildAll"
        run: dotnet run --project tools/builder --no-launch-profile -- BuildAll --timing

      - name: "Upload artifact: test-${{ matrix.os }}"
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}
          path: artifacts/test
        if: always()
